spring:
  profiles:
    active: dev
  config:
    location: classpath:/config/application.yml
  messages:
    basename: i18n/login
  thymeleaf:
    cache: false
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
    #开启HiddenHttpMethodFilter
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    username: root
    password: 15320721xzw12340
    url: jdbc:mysql://localhost:3306/test?serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #druid数据源 其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #   添加此功能不加log4j 依赖会报错
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jpa:
    hibernate:
#      自动创建或更新数据表
      ddl-auto: update
#      显示sql语句
    show-sql: true
  sql:
    init:
      schema-locations: classpath:sql/*.sql
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 8100
  servlet:
    context-path: /springboot
person:
  last-name: 袁天罡${random.int}
  age: 98
  birth: 2021/12/30
  maps: {hobby: 游泳,sport: 溜冰}
  lists:
    -秦时明月之君临天下
    -灵笼
    -野良神
  friend:
    name: ${person.hello:hello}_一歧日和
    age: 22
#debug模式开启自动配置报告，默认值为false
#debug: true
logging:
  level:
    root: info
  file:
    name: springboot.log
---
server:
  port: 8101
spring:
  config:
    activate:
      on-profile: prod
---
server:
  port: 8102
spring:
  config:
    activate:
      on-profile: dev